@startuml
package SUT{
class User{
    - TodoItems: List<TodoItem>
}

class TodoItem {
    - Id: string
    - Description: string
    - Modifications: List<Modification> 
    - DueDate: DateTime
    + ModifyItem(description: string): void
}

class TodoItemService {
    + CreateItem(description: string, dueDate: DateTime): TodoItem
}
class Tag{
    - Title: string
}
class Modification{
    - Timestamp: DateTime
}
}
package DOC{
interface ITodosRepository{
    + FindAllTodoItemsHaveTheSameDueDate(DateTime dueDate): List<TodoItem>
    }
}
User"1" *-- "0..*" TodoItem
TodoItem "1" *-- "0..*" Modification
TodoItem "0..*" --> "0..*" Tag
TodoItemService --> ITodosRepository
TodoItemService --> TodoItem
@enduml
