@startuml
package Core <<Folder>> {
 
    class TodoItem {
        + id : string
        + description : string
        + dueDay : DateTime
        + userId : string
        - tags : List<string>
        + ModificationList : List<Modification> 
        + Modify(description: String): void
    }
    
    entity Modification{
        + timestamp: DateTime
    }
    
    interface ITodosRepository
    {
        + FindAllTodoItemsByUserIdAndDueDay(string userId,DateOnly dueDay) : List<TodoItem>;
        + Insert(TodoItem todoItem):TodoItem;
    }
    
    class TodoItemService
    {
        - _repository : ITodosRepository
        + Create(string description, DateOnly dueDay, string userId):TodoItem;
    }
    enum OptionEnum
    {
        Manual
        Latest
        Freest
    }
    package AppException <<Folder>>
    {
        exception MaximumModificationException
        exception DueDayEarlyException
        exception MaximumSameDueDayException

    }
}
package Infrastructure <<Folder>> {

    class TodoItemMongoRepository implements Core.ITodosRepository{
        + FindAllTodoItemsByUserIdAndDueDay(string userId,DateOnly dueDay) : List<TodoItem>;
        + Insert(TodoItem todoItem):TodoItem;
    }
    
    class TodoItemPo
    {
        + id : string
        + description : string
        + dueDay : DateTime
        + userId : string
        + ModificationList : List<Modification> 
    }

}


TodoItem "1" -- "0..*" Modification
TodoItemPo "1" -- "0..*" Modification

ITodosRepository <.. TodoItemService
@enduml