@startuml TodoItem
 
class TodoItem {
    - id : string
    - description : string
    - dueDay : DateTime
    + userId : string
    - tags : List<string>
    - ModificationList : List<Modification> 
    + Modify(description: String): void
}
class User{
  + userId: string
  - name: string
}
class Modification{
    + timestamp: DateTime
}
class TodosRepository
{
    + FindAllTodoItemsByUserIdAndDueDay(string userId,DateOnly dueDay) : List<TodoItem>;
    + Insert(TodoItem todoItem):TodoItem;
}

class TodoItemService
{
    - _repository : ITodosRepository
    + Create(string description, DateOnly dueDay, string userId):TodoItem;
}
TodoItemService "1" -- "1" TodosRepository
User "1" -- "0..*" TodoItem
TodoItem "1" -- "0..*" Modification
@enduml